// <auto-generated />
using System;
using LMSystem.Repository.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LMSystem.Repository.Migrations
{
    [DbContext(typeof(LMOnlineSystemDbContext))]
    [Migration("20251209185418_update_fb_v15")]
    partial class update_fb_v15
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LMSystem.Repository.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Biography")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CvUrl")
                        .HasColumnType("text");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.Property<string>("LastName")
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParentEmail")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileImg")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character(40)")
                        .IsFixedLength();

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id")
                        .HasName("PK_Account");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.AnswerHistory", b =>
                {
                    b.Property<int>("AnswerHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnswerHistoryId"));

                    b.Property<int>("AnswerSelected")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedStepId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("AnswerHistoryId");

                    b.HasIndex(new[] { "CompletedStepId" }, "IX_AnswerHistory_CompletedStepId");

                    b.HasIndex(new[] { "QuestionId" }, "IX_AnswerHistory_QuestionId");

                    b.ToTable("AnswerHistory", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.ApproveCourse", b =>
                {
                    b.Property<int>("ApproveCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApproveCourseId"));

                    b.Property<DateTime?>("ApproveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApproveStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ApproveCourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("ApproveCourse", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.ArticleComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CommentId")
                        .HasName("PK_ArticleComment");

                    b.HasIndex("AccountId");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleComments", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.ArticleLike", b =>
                {
                    b.Property<int>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LikeId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LikeId")
                        .HasName("PK_ArticleLike");

                    b.HasIndex("AccountId");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleLikes", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.ArticlePost", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BlockReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlockedBy")
                        .HasColumnType("text");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TotalComments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalLikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArticleId")
                        .HasName("PK_ArticlePost");

                    b.HasIndex("AccountId");

                    b.ToTable("ArticlePosts", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.BankAccount", b =>
                {
                    b.Property<int>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BankAccountId"));

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BankAccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Category", b =>
                {
                    b.Property<int>("CatgoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CatgoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Name")
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.Property<int?>("PlacementResultResultId")
                        .HasColumnType("integer");

                    b.HasKey("CatgoryId");

                    b.HasIndex("PlacementResultResultId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("CourseIsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("CourseLevel")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("ImageURL");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("KnowdledgeDescription")
                        .HasColumnType("text");

                    b.Property<string>("LinkCertificated")
                        .HasColumnType("text");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("PublicAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("SalesCampaign")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Title");

                    b.Property<int>("TotalDuration")
                        .HasMaxLength(155)
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoPreviewUrl")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("VideoPreviewURL");

                    b.HasKey("CourseId");

                    b.HasIndex("AccountId");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.CourseCategory", b =>
                {
                    b.Property<int>("CourseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseCategoryId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.HasKey("CourseCategoryId");

                    b.HasIndex(new[] { "CategoryId" }, "IX_CourseCategory_CategoryId");

                    b.HasIndex(new[] { "CourseId" }, "IX_CourseCategory_CourseId");

                    b.ToTable("CourseCategory", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.LinkCertificateAccount", b =>
                {
                    b.Property<int>("LinkCertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LinkCertId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("LinkCert")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LinkCertId");

                    b.HasIndex(new[] { "AccountId" }, "IX_LinkCertificateAccount_AccountId");

                    b.HasIndex(new[] { "CourseId" }, "IX_LinkCertificateAccount_CourseId");

                    b.ToTable("LinkCertificateAccount", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int?>("ModelId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SendDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("NotificationId");

                    b.HasIndex(new[] { "AccountId" }, "IX_Notification_AccountId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountName")
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.Property<string>("Status")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("TransactionNo")
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.HasKey("OrderId");

                    b.HasIndex(new[] { "AccountId" }, "IX_Order_AccountId");

                    b.HasIndex(new[] { "CourseId" }, "IX_Order_CourseId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.PlacementAnswer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnswerId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("ResultId")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResultId");

                    b.ToTable("PlacementAnswer", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.PlacementQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("AnswerOptions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<byte>("DifficultyLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PlacementTestId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("QuestionId");

                    b.HasIndex("PlacementTestId");

                    b.ToTable("PlacementQuestion", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.PlacementResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResultId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PlacementTestId")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("ResultId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PlacementTestId");

                    b.ToTable("PlacementResult", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.PlacementTest", b =>
                {
                    b.Property<int>("PlacementTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlacementTestId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("PlacementTestId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PlacementTest", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("Anwser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CorrectAnwser")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.HasKey("QuestionId");

                    b.HasIndex(new[] { "QuizId" }, "IX_Question_QuizId");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuizId"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("QuizId");

                    b.ToTable("Quiz", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.RatingCourse", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RatingId"));

                    b.Property<string>("CommentContent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool?>("IsRatingStatus")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RatingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RatingStar")
                        .HasColumnType("integer");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("integer");

                    b.HasKey("RatingId");

                    b.HasIndex(new[] { "RegistrationId" }, "IX_RatingCourse_RegistrationId");

                    b.ToTable("RatingCourse", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.RegistrationCourse", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistrationId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("LearningProgress")
                        .HasColumnType("double precision");

                    b.HasKey("RegistrationId");

                    b.HasIndex(new[] { "AccountId" }, "IX_RegistrationCourse_AccountId");

                    b.HasIndex(new[] { "CourseId" }, "IX_RegistrationCourse_CourseId");

                    b.ToTable("RegistrationCourse", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.ReportProblem", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminResponse")
                        .HasColumnType("text");

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int?>("CommentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ProcessedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ReportId");

                    b.HasIndex(new[] { "AccountId" }, "IX_ReportProblem_AccountId");

                    b.ToTable("ReportProblem", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SectionId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.HasKey("SectionId");

                    b.HasIndex(new[] { "CourseId" }, "IX_Section_CourseId");

                    b.ToTable("Section", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Step", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StepId"));

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<int?>("QuizId")
                        .HasColumnType("integer");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer");

                    b.Property<string>("StepDescription")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Title")
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("StepId");

                    b.HasIndex(new[] { "QuizId" }, "IX_Step_QuizId");

                    b.HasIndex(new[] { "SectionId" }, "IX_Step_SectionId");

                    b.ToTable("Step", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.StepCompleted", b =>
                {
                    b.Property<int>("CompletedStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompletedStepId"));

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("integer");

                    b.Property<int>("StepId")
                        .HasColumnType("integer");

                    b.HasKey("CompletedStepId");

                    b.HasIndex(new[] { "RegistrationId" }, "IX_StepCompleted_RegistrationId");

                    b.ToTable("StepCompleted", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.TeacherPayout", b =>
                {
                    b.Property<int>("PayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayoutId"));

                    b.Property<decimal>("AvailableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankAccountHolder")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.Property<string>("BankBranch")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PendingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("PayoutId")
                        .HasName("PK_TeacherPayout");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherPayouts", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.WishList", b =>
                {
                    b.Property<int>("WishListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WishListId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.HasKey("WishListId");

                    b.HasIndex(new[] { "AccountId" }, "IX_WishList_AccountId");

                    b.HasIndex(new[] { "CourseId" }, "IX_WishList_CourseId");

                    b.ToTable("WishList", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LMSystem.Repository.Models.AnswerHistory", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.StepCompleted", "StepCompleted")
                        .WithMany("AnswerHistories")
                        .HasForeignKey("CompletedStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AnswerHistory_StepCompleted");

                    b.HasOne("LMSystem.Repository.Models.Question", "Question")
                        .WithMany("AnswerHistories")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AnswerHistory_Question");

                    b.Navigation("Question");

                    b.Navigation("StepCompleted");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.ApproveCourse", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Course", "Course")
                        .WithMany("ApproveCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.ArticleComment", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMSystem.Repository.Models.ArticlePost", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.ArticleLike", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMSystem.Repository.Models.ArticlePost", "Article")
                        .WithMany("Likes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.ArticlePost", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.BankAccount", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", "Account")
                        .WithMany("BankAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Category", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.PlacementResult", null)
                        .WithMany("Categories")
                        .HasForeignKey("PlacementResultResultId");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Course", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", "Account")
                        .WithMany("Courses")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Course_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.CourseCategory", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Category", "Category")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CourseCategory_Category");

                    b.HasOne("LMSystem.Repository.Models.Course", "Course")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CourseCategory_Course");

                    b.Navigation("Category");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.LinkCertificateAccount", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", "Account")
                        .WithMany("LinkCertificateAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LinkCertificateAccount_Accounts");

                    b.HasOne("LMSystem.Repository.Models.Course", "Course")
                        .WithMany("LinkCertificateAccounts")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LinkCertificateAccount_Course");

                    b.Navigation("Account");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Notification", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notification_Accounts");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Order", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Order_Accounts");

                    b.HasOne("LMSystem.Repository.Models.Course", "Course")
                        .WithMany("Orders")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Order_Course");

                    b.Navigation("Account");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.PlacementAnswer", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.PlacementQuestion", "PlacementQuestion")
                        .WithMany("PlacementAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMSystem.Repository.Models.PlacementResult", "PlacementResult")
                        .WithMany("PlacementAnswers")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlacementQuestion");

                    b.Navigation("PlacementResult");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.PlacementQuestion", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.PlacementTest", "PlacementTest")
                        .WithMany("PlacementQuestions")
                        .HasForeignKey("PlacementTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlacementTest");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.PlacementResult", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", "Account")
                        .WithMany("PlacementResults")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMSystem.Repository.Models.PlacementTest", "PlacementTest")
                        .WithMany("PlacementResults")
                        .HasForeignKey("PlacementTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("PlacementTest");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.PlacementTest", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Category", "Category")
                        .WithMany("PlacementTests")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Question", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Question_Quiz");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.RatingCourse", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.RegistrationCourse", "Registration")
                        .WithMany("RatingCourses")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RatingCourse_RegistrationCourse");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.RegistrationCourse", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", "Account")
                        .WithMany("RegistrationCourses")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RegistrationCourse_Accounts");

                    b.HasOne("LMSystem.Repository.Models.Course", "Course")
                        .WithMany("RegistrationCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RegistrationCourse_Course");

                    b.Navigation("Account");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.ReportProblem", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", "Account")
                        .WithMany("ReportProblems")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReportProblem_Accounts");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Section", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Section_Course");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Step", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Quiz", "Quiz")
                        .WithMany("Steps")
                        .HasForeignKey("QuizId")
                        .HasConstraintName("FK_Step_Quiz");

                    b.HasOne("LMSystem.Repository.Models.Section", "Section")
                        .WithMany("Steps")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Step_Section");

                    b.Navigation("Quiz");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.StepCompleted", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.RegistrationCourse", "Registration")
                        .WithMany("StepCompleteds")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.TeacherPayout", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.WishList", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", "Account")
                        .WithMany("WishLists")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WishList_Accounts");

                    b.HasOne("LMSystem.Repository.Models.Course", "Course")
                        .WithMany("WishLists")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WishList_Course");

                    b.Navigation("Account");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMSystem.Repository.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LMSystem.Repository.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Account", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("Courses");

                    b.Navigation("LinkCertificateAccounts");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("PlacementResults");

                    b.Navigation("RegistrationCourses");

                    b.Navigation("ReportProblems");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.ArticlePost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Category", b =>
                {
                    b.Navigation("CourseCategories");

                    b.Navigation("PlacementTests");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Course", b =>
                {
                    b.Navigation("ApproveCourses");

                    b.Navigation("CourseCategories");

                    b.Navigation("LinkCertificateAccounts");

                    b.Navigation("Orders");

                    b.Navigation("RegistrationCourses");

                    b.Navigation("Sections");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.PlacementQuestion", b =>
                {
                    b.Navigation("PlacementAnswers");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.PlacementResult", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("PlacementAnswers");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.PlacementTest", b =>
                {
                    b.Navigation("PlacementQuestions");

                    b.Navigation("PlacementResults");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Question", b =>
                {
                    b.Navigation("AnswerHistories");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.RegistrationCourse", b =>
                {
                    b.Navigation("RatingCourses");

                    b.Navigation("StepCompleteds");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.Section", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("LMSystem.Repository.Models.StepCompleted", b =>
                {
                    b.Navigation("AnswerHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
